const fs = require('fs');

const Nearley = require('nearley/lib/nearley.js');
const Compile = require('nearley/lib/compile.js');
const Generate = require('nearley/lib/generate.js');
const Unparse = require('./nearley.unparse.js');
const nearleyGrammar = require('nearley/lib/nearley-language-bootstrapped.js');


const resolvePath = (text)=>{
	try{
		if(fs.statSync(text).isFile()) return fs.readFileSync(text, 'utf8');
		return text;
	}catch(e){
		return text;
	}
};

const compileGrammar = (grammar)=>{
	let compiled = Generate(
		Compile(
			(new Nearley.Parser(
					nearleyGrammar.ParserRules,
					nearleyGrammar.ParserStart)
			)
				.feed(grammar)
				.results[0]
		,{})
	).split('\n');

	//Cut off unneeded Nearley generated code
	compiled = compiled.slice(3, compiled.length - 7).join('\n');

	return `const Nearley = require('nearley');

/** Generated by Nearley.js **/
${compiled}
/** End **/

const CompiledParser = new Nearley.Parser(grammar.ParserRules,grammar.ParserStart).grammar;
`;
};


const NearleyThere = {
	compile : (grammar, destination=false)=>{
		const result = `${compileGrammar(resolvePath(grammar))}
module.exports = (input)=>(new Nearley.Parser(CompiledParser)).feed(input).results[0];`;
		if(destination) fs.writeFileSync(destination, result);
		return result;
	},
	parse : (grammar, target)=>{
		const compiledParser = eval(`${compileGrammar(resolvePath(grammar))} CompiledParser;`);
		try{
			return (new Nearley.Parser(compiledParser))
				.feed(target)
				.results[0];
		}catch(err){
			return err;
		}
	},
	unparse : (grammar, depth=5)=>{
		const CompiledGrammar = eval(`${compileGrammar(resolvePath(grammar))} grammar;`);
		try{
			return Unparse(CompiledGrammar, false, depth);
		}catch(err){
			return err;
		}
	},
	generator : (grammar, destination=false)=>{
		const unparse = fs.readFileSync('./nearley.unparse.js', 'utf8').split('\n');
		unparse[unparse.length-1] = `module.exports=(depth)=>unparse(grammar, false, depth);`;
		const result = `${compileGrammar(resolvePath(grammar))} \n ${unparse.join('\n')}`;
		if(destination) fs.writeFileSync(destination, result);
		return result;
	}
};

module.exports = NearleyThere;